// Static translations for all supported languages
const STATIC_TRANSLATIONS = {
  en: {
    summary: "Summary",
    professionalism: "Professionalism",
    favorability: "Favorability",
    deadlinePressure: "Deadline Pressure",
    potentialIssues: "Potential Issues",
    riskLevel: "Risk Level",
    clauseClarity: "Clause Clarity",
    smartSuggestions: "Suggestions",
    mainClauses: "Main Clauses",
    overallScore: "Final Score",
    confidenceToSign: "Confidence to Sign",
    riskStatic: "Based on clause fairness and obligations.",
    clarityStatic: "Reflects how easy the terms are to understand.",
    scoreStatic: "Determines the final score.",
    unsafe: "Unsafe",
    safe: "Safe",
    verySafe: "Very Safe"
  },
  es: {
    summary: "Resumen",
    professionalism: "Profesionalismo",
    favorability: "Favorabilidad",
    deadlinePressure: "Presión de plazo",
    potentialIssues: "Posibles problemas",
    riskLevel: "Nivel de riesgo",
    clauseClarity: "Claridad de cláusulas",
    smartSuggestions: "Sugerencias",
    mainClauses: "Cláusulas principales",
    overallScore: "Puntuación final",
    confidenceToSign: "Confianza para firmar",
    riskStatic: "Basado en equidad y obligaciones.",
    clarityStatic: "Indica qué tan claros son los términos.",
    scoreStatic: "Determina la puntuación final.",
    unsafe: "No seguro",
    safe: "Seguro",
    verySafe: "Muy seguro"
  },
  de: {
    summary: "Zusammenfassung",
    professionalism: "Professionalität",
    favorability: "Vorteilhaftigkeit",
    deadlinePressure: "Zeitdruck",
    potentialIssues: "Mögliche Probleme",
    riskLevel: "Risikostufe",
    clauseClarity: "Klauselklarheit",
    smartSuggestions: "Vorschläge",
    mainClauses: "Hauptklauseln",
    overallScore: "Endbewertung",
    confidenceToSign: "Unterschriftssicherheit",
    riskStatic: "Basierend auf Fairness und Pflichten.",
    clarityStatic: "Zeigt Verständlichkeit der Klauseln.",
    scoreStatic: "Bestimmt die Endbewertung.",
    unsafe: "Unsicher",
    safe: "Sicher",
    verySafe: "Sehr sicher"
  },
  fr: {
    summary: "Résumé",
    professionalism: "Professionnalisme",
    favorability: "Avantage",
    deadlinePressure: "Pression de délai",
    potentialIssues: "Problèmes potentiels",
    riskLevel: "Niveau de risque",
    clauseClarity: "Clarté des clauses",
    smartSuggestions: "Suggestions",
    mainClauses: "Clauses principales",
    overallScore: "Score final",
    confidenceToSign: "Confiance pour signer",
    riskStatic: "Basé sur l’équité et les obligations.",
    clarityStatic: "Indique la clarté des termes.",
    scoreStatic: "Détermine le score final.",
    unsafe: "Risqué",
    safe: "Sûr",
    verySafe: "Très sûr"
  },
        it: {
          summary: "Riepilogo",
          professionalism: "Professionalità",
          favorability: "Convenienza",
          deadlinePressure: "Pressione scadenze",
          potentialIssues: "Problemi potenziali",
          riskLevel: "Livello di rischio",
          clauseClarity: "Chiarezza clausole",
          smartSuggestions: "Suggerimenti",
          mainClauses: "Clausole principali",
          overallScore: "Punteggio finale",
          confidenceToSign: "Fiducia alla firma",
          riskStatic: "Basato su equità e obblighi.",
          clarityStatic: "Indica quanto sono chiari i termini.",
          scoreStatic: "Determina il punteggio finale.",
          unsafe: "Rischioso",
          safe: "Sicuro",
          verySafe: "Molto sicuro"
        },
        pt: {
          summary: "Resumo",
          professionalism: "Profissionalismo",
          favorability: "Vantagem",
          deadlinePressure: "Pressão de prazo",
          potentialIssues: "Possíveis problemas",
          riskLevel: "Nível de risco",
          clauseClarity: "Clareza das cláusulas",
          smartSuggestions: "Sugestões",
          mainClauses: "Cláusulas principais",
          overallScore: "Pontuação final",
          confidenceToSign: "Confiança para assinar",
          riskStatic: "Baseado em justiça e obrigações.",
          clarityStatic: "Mostra a clareza dos termos.",
          scoreStatic: "Define a pontuação final.",
          unsafe: "Arriscado",
          safe: "Seguro",
          verySafe: "Muito seguro"
        },
        nl: {
          summary: "Samenvatting",
          professionalism: "Professionaliteit",
          favorability: "Voordeel",
          deadlinePressure: "Tijdsdruk",
          potentialIssues: "Mogelijke problemen",
          riskLevel: "Risiconiveau",
          clauseClarity: "Clausuleduidelijkheid",
          smartSuggestions: "Suggesties",
          mainClauses: "Hoofdclausules",
          overallScore: "Eindscore",
          confidenceToSign: "Vertrouwen om te tekenen",
          riskStatic: "Gebaseerd op eerlijkheid en plichten.",
          clarityStatic: "Geeft duidelijkheid van voorwaarden aan.",
          scoreStatic: "Bepaalt de eindscore.",
          unsafe: "Onveilig",
          safe: "Veilig",
          verySafe: "Zeer veilig"
        },
        ro: {
          summary: "Rezumat",
          professionalism: "Profesionalism",
          favorability: "Avantaj",
          deadlinePressure: "Presiune termen",
          potentialIssues: "Probleme posibile",
          riskLevel: "Nivel de risc",
          clauseClarity: "Claritate clauze",
          smartSuggestions: "Sugestii",
          mainClauses: "Clauze principale",
          overallScore: "Scor final",
          confidenceToSign: "Încredere la semnare",
          riskStatic: "Bazat pe echitate și obligații.",
          clarityStatic: "Arată cât de clare sunt condițiile.",
          scoreStatic: "Determină scorul final.",
          unsafe: "Nesigur",
          safe: "Sigur",
          verySafe: "Foarte sigur"
        },
        sq: {
          summary: "Përmbledhje",
          professionalism: "Profesionalizëm",
          favorability: "Përfitim",
          deadlinePressure: "Presion afati",
          potentialIssues: "Probleme të mundshme",
          riskLevel: "Niveli i rrezikut",
          clauseClarity: "Qartësi klauzolash",
          smartSuggestions: "Sugjerime",
          mainClauses: "Klauzola kryesore",
          overallScore: "Rezultati final",
          confidenceToSign: "Besim për nënshkrim",
          riskStatic: "Bazuar në drejtësi dhe detyrime.",
          clarityStatic: "Tregon sa të qarta janë kushtet.",
          scoreStatic: "Përcakton rezultatin final.",
          unsafe: "I pasigurt",
          safe: "I sigurt",
          verySafe: "Shumë i sigurt"
        },
        zh: {
          summary: "摘要",
          professionalism: "专业性",
          favorability: "有利性",
          deadlinePressure: "期限压力",
          potentialIssues: "潜在问题",
          riskLevel: "风险等级",
          clauseClarity: "条款清晰度",
          smartSuggestions: "建议",
          mainClauses: "主要条款",
          overallScore: "最终评分",
          confidenceToSign: "签署信心",
          riskStatic: "基于条款公平性和义务。",
          clarityStatic: "反映条款理解难度。",
          scoreStatic: "决定最终评分。",
          unsafe: "不安全",
          safe: "安全",
          verySafe: "非常安全"
        },
        ja: {
          summary: "要約",
          professionalism: "専門性",
          favorability: "有利性",
          deadlinePressure: "期限圧力",
          potentialIssues: "潜在的な問題",
          riskLevel: "リスクレベル",
          clauseClarity: "条項の明確さ",
          smartSuggestions: "提案",
          mainClauses: "主要条項",
          overallScore: "最終スコア",
          confidenceToSign: "署名の信頼度",
          riskStatic: "条項の公平性と義務に基づく。",
          clarityStatic: "条項の分かりやすさを示す。",
          scoreStatic: "最終スコアを決定。",
          unsafe: "危険",
          safe: "安全",
          verySafe: "非常に安全"
        },
        tr: {
          summary: "Özet",
          professionalism: "Profesyonellik",
          favorability: "Avantaj",
          deadlinePressure: "Süre baskısı",
          potentialIssues: "Olası sorunlar",
          riskLevel: "Risk seviyesi",
          clauseClarity: "Madde açıklığı",
          smartSuggestions: "Öneriler",
          mainClauses: "Ana maddeler",
          overallScore: "Final puanı",
          confidenceToSign: "İmzalama güveni",
          riskStatic: "Adalet ve yükümlülüklere dayanır.",
          clarityStatic: "Şartların anlaşılmasını gösterir.",
          scoreStatic: "Final puanı belirler.",
          unsafe: "Riskli",
          safe: "Güvenli",
          verySafe: "Çok güvenli"
        }
      };
